[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "dbus",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libXrender",
  "cups",
  "libdrm",
  "mesa",
  "alsa-lib",
  "at-spi2-atk",
  "at-spi2-core",
  "atk",
  "pango",
  "cairo",
  "gtk3",
  "nspr",
  "expat"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node server.js"
